#!/bin/sh


create-dmg \
  --volname "sub.live installer" \
  --volicon "./icon.icns" \
  --background "./background.jpg" \
  --window-pos 200 120 \
  --window-size 600 400 \
  --icon-size 100 \
  --no-internet-enable \
  --icon "sub.live.app" 100 175 \
  --hide-extension "sub.live.app" \
  --app-drop-link 460 175 \
  "sub.live.dmg" \
  "sub.live.app/"

